# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lints and Tests 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - uses: hadolint/hadolint-action@v1.5.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8
    - name: Run linters
      run: |
        poetry install
        poetry run black --check pluploader/
        poetry run isort --check pluploader/
        poetry run flake8 --count pluploader/
    - name: Run pluploader --version
      run: |
        poetry run pluploader --version
